services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000" 
    environment:
      NODE_ENV: production
    volumes:
      - /app/node_modules # Avoid overwriting node_modules
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Create a custom bridge network for internal communication

volumes:
  db:
    driver: local